# -*- coding: utf-8 -*-
"""sayı_tahmini_ödev

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vDbHuV9PapgXmXHbQCmBEFKDCWdEQTf7
"""

import random

sehirler=["Adana","Adıyaman","Afyon","Ağrı","Amasya","Ankara","Antalya","Artvin","Aydın","Balıkesir","Bilecik","Bingöl","Bitlis","Bolu","Burdur",
"Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Edirne","Elazığ",
"Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkari",
"Hatay","Isparta","Mersin", "İstanbul","İzmir","Kars","Kastamonu","Kayseri",
"Kırklareli","Kırşehir","Kocaeli","Konya","Kütahya","Malatya","Manisa",
"Kahramanmaraş","Mardin","Muğla","Muş","Nevşehir","Niğde","Ordu","Rize","Sakarya",
"Samsun", "Siirt","Sinop","Sivas","Tekirdağ","Tokat","Trabzon","Tunceli",
"Şanlıurfa","Uşak","Van","Yozgat","Zonguldak","Aksaray","Bayburt","Karaman",
"Kırıkkale","Batman","Şırnak","Bartın","Ardahan","Iğdır","Yalova","Karabük",
"Kilis","Osmaniye","Düzce"]
def oyuncu_isimleri():
  flag= True
  a=0
  puan1=100
  puan2=100
  ilk_oyuncu=input("ilk oyuncunun ismi: ")
  ikinci_oyuncu= input("ikinci oyuncunun ismi: ")
  x=random.randint(1,81)
  z=random.randint(1,81)
  print("Başlangıçta 100 puanınız vardır.") 
  while flag:
    giris_bilgi=int(input("{} sayı tahminini girer misin?: ".format(ilk_oyuncu))) 
    print("Random sayı: ",x)

    if giris_bilgi == x:
      print("{} kazandı tebrik ederim.".format(ilk_oyuncu))
      while True :
        giris_bilgi=int(input("{} sayı tahminini girer misin?: ".format(ikinci_oyuncu)))
        print("Random sayı: ",z)
        
        if giris_bilgi == z:
          print("{} kazandı tebrik ederim.".format(ikinci_oyuncu))
          print("-----------------------------------------------")
          print("oyun sonucu; ")
          print("{}:{}  ".format(ilk_oyuncu,puan1))
          print("{}:{}  ".format(ikinci_oyuncu,puan2))
          if puan1 < puan2:
            print("Tebrikler {} kazandı.".format(ilk_oyuncu))
            flag=False
            break
          elif puan1 == "Başarısız" and puan2 == "Başarısız":
            print("Üzgünüz ikiniz de kaybettiğiniz")
            flag=False
            break
          elif puan1 == "Başarısız":
            print("{} kazandı,tebrik ederiz".format(ikinci_oyuncu))
            flag=False
            break
          elif puan2 == "Başarısız":
            print("{} kazandı,tebrik ederiz".format(ilk_oyuncu))
            flag=False
            break
          elif puan1 == puan2:
            print("İkiniz de kazandınız")
            flag=False
            break
          print("-----------------------------------------------")

        else:
          puan2 = puan2 - 10
          if puan1 == 0:
            puan1="Başarısız"
          else:
            tahmin2=random.randint(z-3,z+3)
            print("Şehir tahmini: ",tahmin2)
          
          if tahmin2 == giris_bilgi:
            tahmin= random.randint(z-3,z+3) 
            print("Şehir tahmini: ",tahmin2)
          else:
            print("puanınız: ",puan2)
            print("tahmin ettiğin yer {} Uzak Kaldı: ".format(sehirler[tahmin2])) 


    else:
      puan1 = puan1 -10
      if puan1 == 0:
        puan1="Başarısız"
      else:
        tahmin= random.randint(x-3,x+3)
        print("Şehir tahmini: ",tahmin)

      if tahmin == giris_bilgi:
        tahmin = random.randint( x-3,x+3)
        print("Şehir tahmini: ",tahmin)
        
      else:
        print("puanınız: ",puan1)
        print("tahmin ettiğin yer {} Uzak Kaldı: ".format(sehirler[tahmin]))

 

oyuncu_isimleri()